const express=require('express')
const rt=require('./route')
const cors=require('cors')
const app=express()
app.use(express.urlencoded({extended:false}))
app.use(express.json())
app.use(cors())
app.use('/',rt)
app.listen(8000,()=>{
    console.log('server is running...')
})